### ISSUE TITLE
Sync targets

### ISSUE THREAD

**Issue by paradoxuum** [jackTabsCode/asphalt#40]
Tarmac has a flag called `--target` with four options: `roblox`, `local`, `none` and `debug`.

It might be useful to have these options when syncing with Asphalt as well, maybe like the following:
- `roblox`: The current behaviour, sync to Roblox using Open Cloud
- `local`: Sync the assets to a folder accessible within Roblox Studio
- `none`: Don't sync to anything, useful for dry runs to check if anything needs to be uploaded
- `debug`: In this case, it looks like Tarmac syncs assets to a folder called `.tarmac_debug` in the working directory, I'm not sure how necessary this option is but it might be useful for debugging purposes (as the name suggests)

I think the `local` target should avoid writing anything to the lockfile however, or maybe just use a default `asset_id` if the entry doesn't exist, as it's primarily used for testing assets. I think this is how tarmac does it, at least.

Tarmac uses the [roblox-install](https://github.com/Kampfkarren/roblox-install/tree/master) crate to get Studio's installation path, in order to sync assets to the `content` directory when using the `local` sync target.

**Comment by jackTabsCode** [comment]
Local targets is something I'm currently working on!

**Comment by jackTabsCode** [comment]
I unassigned myself from the issue. I probably don't have time to work on this right now. If anyone else is interested in this feature, they're welcome to take a stab at it.

If animations are detected during the sync phase, we'll probably want to warn the user they won't work with a local target.

cc @paradoxuum
