### ISSUE TITLE
Support tab indentation

### ISSUE THREAD

**Issue by spectrius** [jackTabsCode/asphalt#77]
Asphalt currently only supports spaces which makes my formatter go haywire, would be useful if you could choose to indent with tabs

Additionally, when indenting with spaces, there should be an option to change how many spaces are used per indent

**Comment by jackTabsCode** [comment]
@spectrius I think having formatting options is a rabbit hole we don't want to go into. Consider ignoring Asphalt's generated files with your formatter.

If you're using `stylua`, you can create a `.styluaignore` file and add the generated file path to it.
